### PR TITLE
Fixed the title

### PR DESCRIPTION
**Pull request by JayjeetAtGithub**

### CODE REVIEW

**Comment by JayjeetAtGithub** [comment]
@ankan17

**Comment by ghoshbishakh** [comment]
TIP:
In future, in the commit message add something like   ->   closes #40 
Github will automatically pick it up and link with the issue

**Comment by arc9693** [comment]
@ghoshbishakh  Yes, I follow it generally. I was just gonna reference the issue but got busy on another tab. Will keep in mind from the next time. Thanks for pointing out. :)

**Comment by realsdx** [comment]
Finally merged! Yay!!!

**Comment by ghoshbishakh** [comment]
@realsdx why you so happy ?? :P

**Pull request merged**
