### PR TITLE
Timeline Feature Added

### PR DESCRIPTION
**Pull request by SucharuRai**

### CODE REVIEW

**Comment by realsdx** [comment]
Remove dark theme, as our website itself is based on a light theme.
And placement of logos (club logo and time logo) is not balanced.
Add some 'interactive' properties in elements like shadows or zoom, etc.

**Review by arc9693 — CHANGES_REQUESTED** [review]
Good work. Here are some changes you have to make:
- [ ] Change the theme of the page to match the theme of the website.
- [ ] Add the logic to hide the preloader (when page is refreshed the preloader never stops running)

**Review by arc9693 — CHANGES_REQUESTED** [review]
Correct the responsiveness. The mobile view font is huge and overflowing.

**Review by arc9693 — CHANGES_REQUESTED** [review]
@SucharuRai It looks good. Can you just change the z-index of the logo so that it stays behind the nav-bar in mobile view?
Also kindly add node-sass as dev dependency.

**Comment by arc9693** [comment]
Good work @SucharuRai

**Pull request merged**
